### ISSUE TITLE
Works indefinitely when processing file

### ISSUE THREAD

**Issue by srghma** [threedaymonk/htmlbeautifier#50]
`$ htmlbeautifier app/views/project/_summary.html.erb
`
indefinitely long 
[_summary.html.erb.txt](https://github.com/threedaymonk/htmlbeautifier/files/2455470/_summary.html.erb.txt)

Please rename _summary.html.erb.txt to _summary.html.erb

```
$ gem which htmlbeautifier
/home/srghma/.gem/ruby/2.4.0/gems/htmlbeautifier-1.3.1/lib/htmlbeautifier.rb

```

Then I click ctrl-c

```
$ htmlbeautifier app/views/project/_summary.html.erb
^C/home/srghma/.gem/ruby/2.4.0/gems/htmlbeautifier-1.3.1/lib/htmlbeautifier/parser.rb:30:in `scan': Interrupt
        from /home/srghma/.gem/ruby/2.4.0/gems/htmlbeautifier-1.3.1/lib/htmlbeautifier/parser.rb:30:in `block in dispatch'
        from /home/srghma/.gem/ruby/2.4.0/gems/htmlbeautifier-1.3.1/lib/htmlbeautifier/parser.rb:30:in `each'
        from /home/srghma/.gem/ruby/2.4.0/gems/htmlbeautifier-1.3.1/lib/htmlbeautifier/parser.rb:30:in `find'
        from /home/srghma/.gem/ruby/2.4.0/gems/htmlbeautifier-1.3.1/lib/htmlbeautifier/parser.rb:30:in `dispatch'
        from /home/srghma/.gem/ruby/2.4.0/gems/htmlbeautifier-1.3.1/lib/htmlbeautifier/parser.rb:16:in `scan'
        from /home/srghma/.gem/ruby/2.4.0/gems/htmlbeautifier-1.3.1/lib/htmlbeautifier.rb:26:in `block in beautify'
        from /home/srghma/.gem/ruby/2.4.0/gems/htmlbeautifier-1.3.1/lib/htmlbeautifier.rb:25:in `tap'
        from /home/srghma/.gem/ruby/2.4.0/gems/htmlbeautifier-1.3.1/lib/htmlbeautifier.rb:25:in `beautify'
        from /home/srghma/.gem/ruby/2.4.0/gems/htmlbeautifier-1.3.1/bin/htmlbeautifier:7:in `beautify'
        from /home/srghma/.gem/ruby/2.4.0/gems/htmlbeautifier-1.3.1/bin/htmlbeautifier:74:in `block (2 levels) in <top (required)>'
        from /home/srghma/.gem/ruby/2.4.0/gems/htmlbeautifier-1.3.1/bin/htmlbeautifier:73:in `open'
        from /home/srghma/.gem/ruby/2.4.0/gems/htmlbeautifier-1.3.1/bin/htmlbeautifier:73:in `block in <top (required)>'
        from /home/srghma/.gem/ruby/2.4.0/gems/htmlbeautifier-1.3.1/bin/htmlbeautifier:70:in `each'
        from /home/srghma/.gem/ruby/2.4.0/gems/htmlbeautifier-1.3.1/bin/htmlbeautifier:70:in `<top (required)>'
        from /home/srghma/.gem/ruby/2.4.0/bin/htmlbeautifier:23:in `load'
        from /home/srghma/.gem/ruby/2.4.0/bin/htmlbeautifier:23:in `<main>'

```

**Comment by threedaymonk** [comment]
Should be fixed in 1.4.0. Please let me know if not.
