### ISSUE TITLE
crash on explicit self-closing tags

### ISSUE THREAD

**Issue by bertBruynooghe** [threedaymonk/htmlbeautifier#87]
formatting:
```
<template>
  <input
    class="btn"
  />
</template>
```

gives me following crash report:
```
bundler: failed to load command: htmlbeautifier (/wip/backend/vendor/bundle/ruby/3.2.0/bin/htmlbeautifier)
/wip/backend/vendor/bundle/ruby/3.2.0/gems/htmlbeautifier-1.4.3/bin/htmlbeautifier:12:in `rescue in beautify': Error parsing app/views/pages/_wind_farms.html.erb: Unmatched sequence on line 2 (RuntimeError)
        from /wip/backend/vendor/bundle/ruby/3.2.0/gems/htmlbeautifier-1.4.3/bin/htmlbeautifier:9:in `beautify'
        from /wip/backend/vendor/bundle/ruby/3.2.0/gems/htmlbeautifier-1.4.3/bin/htmlbeautifier:98:in `block (2 levels) in <top (required)>'
        from /wip/backend/vendor/bundle/ruby/3.2.0/gems/htmlbeautifier-1.4.3/bin/htmlbeautifier:97:in `open'
        from /wip/backend/vendor/bundle/ruby/3.2.0/gems/htmlbeautifier-1.4.3/bin/htmlbeautifier:97:in `block in <top (required)>'
        from /wip/backend/vendor/bundle/ruby/3.2.0/gems/htmlbeautifier-1.4.3/bin/htmlbeautifier:89:in `each'
        from /wip/backend/vendor/bundle/ruby/3.2.0/gems/htmlbeautifier-1.4.3/bin/htmlbeautifier:89:in `<top (required)>'
        from /wip/backend/vendor/bundle/ruby/3.2.0/bin/htmlbeautifier:25:in `load'
        from /wip/backend/vendor/bundle/ruby/3.2.0/bin/htmlbeautifier:25:in `<top (required)>'
        from /wip/backend/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.1/lib/bundler/cli/exec.rb:58:in `load'
        from /wip/backend/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.1/lib/bundler/cli/exec.rb:58:in `kernel_load'
        from /wip/backend/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.1/lib/bundler/cli/exec.rb:23:in `run'
        from /wip/backend/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.1/lib/bundler/cli.rb:491:in `exec'
        from /wip/backend/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.1/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
        from /wip/backend/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.1/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
        from /wip/backend/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.1/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
        from /wip/backend/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.1/lib/bundler/cli.rb:34:in `dispatch'
        from /wip/backend/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.1/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
        from /wip/backend/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.1/lib/bundler/cli.rb:28:in `start'
        from /wip/backend/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.1/exe/bundle:45:in `block in <top (required)>'
        from /wip/backend/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.1/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
        from /wip/backend/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.1/exe/bundle:33:in `<top (required)>'
        from /usr/local/bin/bundle:25:in `load'
        from /usr/local/bin/bundle:25:in `<main>'
/wip/backend/vendor/bundle/ruby/3.2.0/gems/htmlbeautifier-1.4.3/lib/htmlbeautifier/parser.rb:37:in `rescue in dispatch': Unmatched sequence on line 2 (RuntimeError)
        from /wip/backend/vendor/bundle/ruby/3.2.0/gems/htmlbeautifier-1.4.3/lib/htmlbeautifier/parser.rb:31:in `dispatch'
        from /wip/backend/vendor/bundle/ruby/3.2.0/gems/htmlbeautifier-1.4.3/lib/htmlbeautifier/parser.rb:18:in `scan'
        from /wip/backend/vendor/bundle/ruby/3.2.0/gems/htmlbeautifier-1.4.3/lib/htmlbeautifier.rb:28:in `block in beautify'
        from <internal:kernel>:90:in `tap'
        from /wip/backend/vendor/bundle/ruby/3.2.0/gems/htmlbeautifier-1.4.3/lib/htmlbeautifier.rb:27:in `beautify'
        from /wip/backend/vendor/bundle/ruby/3.2.0/gems/htmlbeautifier-1.4.3/bin/htmlbeautifier:10:in `beautify'
        from /wip/backend/vendor/bundle/ruby/3.2.0/gems/htmlbeautifier-1.4.3/bin/htmlbeautifier:98:in `block (2 levels) in <top (required)>'
        from /wip/backend/vendor/bundle/ruby/3.2.0/gems/htmlbeautifier-1.4.3/bin/htmlbeautifier:97:in `open'
        from /wip/backend/vendor/bundle/ruby/3.2.0/gems/htmlbeautifier-1.4.3/bin/htmlbeautifier:97:in `block in <top (required)>'
        from /wip/backend/vendor/bundle/ruby/3.2.0/gems/htmlbeautifier-1.4.3/bin/htmlbeautifier:89:in `each'
        from /wip/backend/vendor/bundle/ruby/3.2.0/gems/htmlbeautifier-1.4.3/bin/htmlbeautifier:89:in `<top (required)>'
        from /wip/backend/vendor/bundle/ruby/3.2.0/bin/htmlbeautifier:25:in `load'
        from /wip/backend/vendor/bundle/ruby/3.2.0/bin/htmlbeautifier:25:in `<top (required)>'
        from /wip/backend/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.1/lib/bundler/cli/exec.rb:58:in `load'
        from /wip/backend/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.1/lib/bundler/cli/exec.rb:58:in `kernel_load'
        from /wip/backend/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.1/lib/bundler/cli/exec.rb:23:in `run'
        from /wip/backend/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.1/lib/bundler/cli.rb:491:in `exec'
        from /wip/backend/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.1/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
        from /wip/backend/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.1/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
        from /wip/backend/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.1/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
        from /wip/backend/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.1/lib/bundler/cli.rb:34:in `dispatch'
        from /wip/backend/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.1/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
        from /wip/backend/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.1/lib/bundler/cli.rb:28:in `start'
        from /wip/backend/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.1/exe/bundle:45:in `block in <top (required)>'
        from /wip/backend/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.1/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
        from /wip/backend/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.1/exe/bundle:33:in `<top (required)>'
        from /usr/local/bin/bundle:25:in `load'
        from /usr/local/bin/bundle:25:in `<main>'
/wip/backend/vendor/bundle/ruby/3.2.0/gems/htmlbeautifier-1.4.3/lib/htmlbeautifier/parser.rb:33:in `dispatch': Unmatched sequence (RuntimeError)
        from /wip/backend/vendor/bundle/ruby/3.2.0/gems/htmlbeautifier-1.4.3/lib/htmlbeautifier/parser.rb:18:in `scan'
        from /wip/backend/vendor/bundle/ruby/3.2.0/gems/htmlbeautifier-1.4.3/lib/htmlbeautifier.rb:28:in `block in beautify'
        from <internal:kernel>:90:in `tap'
        from /wip/backend/vendor/bundle/ruby/3.2.0/gems/htmlbeautifier-1.4.3/lib/htmlbeautifier.rb:27:in `beautify'
        from /wip/backend/vendor/bundle/ruby/3.2.0/gems/htmlbeautifier-1.4.3/bin/htmlbeautifier:10:in `beautify'
        from /wip/backend/vendor/bundle/ruby/3.2.0/gems/htmlbeautifier-1.4.3/bin/htmlbeautifier:98:in `block (2 levels) in <top (required)>'
        from /wip/backend/vendor/bundle/ruby/3.2.0/gems/htmlbeautifier-1.4.3/bin/htmlbeautifier:97:in `open'
        from /wip/backend/vendor/bundle/ruby/3.2.0/gems/htmlbeautifier-1.4.3/bin/htmlbeautifier:97:in `block in <top (required)>'
        from /wip/backend/vendor/bundle/ruby/3.2.0/gems/htmlbeautifier-1.4.3/bin/htmlbeautifier:89:in `each'
        from /wip/backend/vendor/bundle/ruby/3.2.0/gems/htmlbeautifier-1.4.3/bin/htmlbeautifier:89:in `<top (required)>'
        from /wip/backend/vendor/bundle/ruby/3.2.0/bin/htmlbeautifier:25:in `load'
        from /wip/backend/vendor/bundle/ruby/3.2.0/bin/htmlbeautifier:25:in `<top (required)>'
        from /wip/backend/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.1/lib/bundler/cli/exec.rb:58:in `load'
        from /wip/backend/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.1/lib/bundler/cli/exec.rb:58:in `kernel_load'
        from /wip/backend/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.1/lib/bundler/cli/exec.rb:23:in `run'
        from /wip/backend/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.1/lib/bundler/cli.rb:491:in `exec'
        from /wip/backend/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.1/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
        from /wip/backend/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.1/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
        from /wip/backend/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.1/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
        from /wip/backend/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.1/lib/bundler/cli.rb:34:in `dispatch'
        from /wip/backend/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.1/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
        from /wip/backend/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.1/lib/bundler/cli.rb:28:in `start'
        from /wip/backend/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.1/exe/bundle:45:in `block in <top (required)>'
        from /wip/backend/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.1/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
        from /wip/backend/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.1/exe/bundle:33:in `<top (required)>'
        from /usr/local/bin/bundle:25:in `load'
        from /usr/local/bin/bundle:25:in `<main>'
```

**Comment by jmvallet** [comment]
The same error occurs for legitimate SVG code, such as:  `<svg><rect /></svg>`, `<svg><path /></svg>`, ...
